#!/bin/bash

job_configure_users()
{
	msg_job_start "job_configure_users"

        trap 'api_fs_umount "${mountpoint}" 2>/dev/null' EXIT
        api_fs_mount "${mountpoint}"

	msg "create bundle group"
	chroot ${mountpoint} /usr/sbin/groupadd bundle

	msg "setup the user's groups"

	chroot ${mountpoint} /usr/bin/gpasswd -a ${user_name} users
	chroot ${mountpoint} /usr/bin/gpasswd -a ${user_name} audio
	chroot ${mountpoint} /usr/bin/gpasswd -a ${user_name} video
	chroot ${mountpoint} /usr/bin/gpasswd -a ${user_name} network
	chroot ${mountpoint} /usr/bin/gpasswd -a ${user_name} optical
	chroot ${mountpoint} /usr/bin/gpasswd -a ${user_name} floppy
	chroot ${mountpoint} /usr/bin/gpasswd -a ${user_name} lp
	chroot ${mountpoint} /usr/bin/gpasswd -a ${user_name} log
	chroot ${mountpoint} /usr/bin/gpasswd -a ${user_name} power
	chroot ${mountpoint} /usr/bin/gpasswd -a ${user_name} scanner
	chroot ${mountpoint} /usr/bin/gpasswd -a ${user_name} storage
	chroot ${mountpoint} /usr/bin/gpasswd -a ${user_name} locate
	chroot ${mountpoint} /usr/bin/gpasswd -a ${user_name} bundle

	msg "create common dirs"
	chroot ${mountpoint} /bin/mkdir -p -v /home/${user_name}/Desktop
	chroot ${mountpoint} /bin/mkdir -p -v /home/${user_name}/Documents
	chroot ${mountpoint} /bin/mkdir -p -v /home/${user_name}/Downloads
	chroot ${mountpoint} /bin/mkdir -p -v /home/${user_name}/Images
	chroot ${mountpoint} /bin/mkdir -p -v /home/${user_name}/Music
	chroot ${mountpoint} /bin/mkdir -p -v /home/${user_name}/Video
	chroot ${mountpoint} /bin/mkdir -p -v /home/${user_name}/.kde4/Autostart
	chroot ${mountpoint} /bin/mkdir -p -v /home/${user_name}/.kde4/env
	chroot ${mountpoint} /bin/mkdir -p -v /home/${user_name}/.kde4/share/config
	chroot ${mountpoint} /bin/mkdir -p -v /home/${user_name}/.kde4/share/apps/konqueror
	chroot ${mountpoint} /bin/mkdir -p -v /home/${user_name}/.local/share/applications
	chroot ${mountpoint} /bin/mkdir -p -v /home/${user_name}/.kde4/share/kde4/services/searchproviders
	chroot ${mountpoint} /bin/mkdir -p -v /home/${user_name}/.config/autostart

	timestamp=`date +%F-%H%M%S`
	chroot ${mountpoint} /bin/mkdir -p -v /home/${user_name}/.backup/${timestamp}

	msg "backup user files"
	if [ -e ${mountpoint}/home/${user_name}/.kde4/share/config/ksplashrc ] ; then
	    mv -v ${mountpoint}/home/${user_name}/.kde4/share/config/ksplashrc ${mountpoint}/home/${user_name}/.backup/${timestamp}/
	fi
	if [ -e ${mountpoint}/home/${user_name}/.kde4/share/config/plasma-desktop-appletsrc ] ; then
	    mv -v ${mountpoint}/home/${user_name}/.kde4/share/config/plasma-desktop-appletsrc ${mountpoint}/home/${user_name}/.backup/${timestamp}/
	fi
	if [ -e ${mountpoint}/home/${user_name}/.kde4/share/config/plasmarc ] ; then
	    mv -v ${mountpoint}/home/${user_name}/.kde4/share/config/plasmarc ${mountpoint}/home/${user_name}/.backup/${timestamp}/
	fi
	if [ -e ${mountpoint}/home/${user_name}/.kde4/share/config/kcmfonts ] ; then
	    mv -v ${mountpoint}/home/${user_name}/.kde4/share/config/kcmfonts ${mountpoint}/home/${user_name}/.backup/${timestamp}/
	fi
	if [ -e ${mountpoint}/home/${user_name}/.kde4/share/apps/konqueror/bookmarks.xml ] ; then
	    mv -v ${mountpoint}/home/${user_name}/.kde4/share/apps/konqueror/bookmarks.xml ${mountpoint}/home/${user_name}/.backup/${timestamp}/
	fi
	if [ -e ${mountpoint}/home/${user_name}/.kde4/share/config/rekonqrc ] ; then
	    mv -v ${mountpoint}/home/${user_name}/.kde4/share/config/rekonqrc ${mountpoint}/home/${user_name}/.backup/${timestamp}/
	fi
	if [ -e ${mountpoint}/home/${user_name}/.kde4/share/config/khotkeysrc ] ; then
	    mv -v ${mountpoint}/home/${user_name}/.kde4/share/config/khotkeysrc ${mountpoint}/home/${user_name}/.backup/${timestamp}/
	fi
	if [ -e ${mountpoint}/home/${user_name}/.kde4/share/config/kglobalshortcutsrc ] ; then
	    mv -v ${mountpoint}/home/${user_name}/.kde4/share/config/kglobalshortcutsrc ${mountpoint}/home/${user_name}/.backup/${timestamp}/
	fi
	if [ -e ${mountpoint}/home/${user_name}/.kde4/share/config/yakuakerc ] ; then
	    mv -v ${mountpoint}/home/${user_name}/.kde4/share/config/yakuakerc ${mountpoint}/home/${user_name}/.backup/${timestamp}/
	fi
	if [ -e ${mountpoint}/home/${user_name}/.kde4/share/config/kickoffrc ] ; then
	    mv -v ${mountpoint}/home/${user_name}/.kde4/share/config/kickoffrc ${mountpoint}/home/${user_name}/.backup/${timestamp}/
	fi
	if [ -e ${mountpoint}/home/${user_name}/.kde4/share/config/networkmanagementrc ] ; then
	    mv -v ${mountpoint}/home/${user_name}/.kde4/share/config/networkmanagementrc ${mountpoint}/home/${user_name}/.backup/${timestamp}/
	fi
	if [ -e ${mountpoint}/home/${user_name}/.bashrc ] ; then
	    mv -v ${mountpoint}/home/${user_name}/.bashrc ${mountpoint}/home/${user_name}/.backup/${timestamp}/
	fi
	if [ -e ${mountpoint}/home/${user_name}/.local/share/applications/mimeapps.list ] ; then
	    mv -v ${mountpoint}/home/${user_name}/.local/share/applications/mimeapps.list ${mountpoint}/home/${user_name}/.backup/${timestamp}/
	fi
	if [ -e ${mountpoint}/home/${user_name}/.kde4/share/config/kcminputrc ] ; then
	    mv -v ${mountpoint}/home/${user_name}/.kde4/share/config/kcminputrc ${mountpoint}/home/${user_name}/.backup/${timestamp}/
	fi
	if [ -e ${mountpoint}/home/${user_name}/.kde4/share/config/kdeglobals ] ; then
	    mv -v ${mountpoint}/home/${user_name}/.kde4/share/config/kdeglobals ${mountpoint}/home/${user_name}/.backup/${timestamp}/
	fi

	msg "setup KaOS settings"
	cp -vf /etc/skel/ksplashrc ${mountpoint}/home/${user_name}/.kde4/share/config/ksplashrc
	cp -vf /etc/skel/kcminputrc ${mountpoint}/home/${user_name}/.kde4/share/config/kcminputrc
	cp -vf /etc/skel/kwinrc ${mountpoint}/home/${user_name}/.kde4/share/config/kwinrc
	cp -vf /etc/skel/plasma-desktop-appletsrc ${mountpoint}/home/${user_name}/.kde4/share/config/plasma-desktop-appletsrc
	cp -vf /etc/skel/plasmarc ${mountpoint}/home/${user_name}/.kde4/share/config/plasmarc
	cp -vf /etc/skel/kcmfonts ${mountpoint}/home/${user_name}/.kde4/share/config/kcmfonts
	cp -vf /etc/skel/bookmarks.xml ${mountpoint}/home/${user_name}/.kde4/share/apps/konqueror/bookmarks.xml
	cp -vf /etc/skel/rekonqrc ${mountpoint}/home/${user_name}/.kde4/share/config/rekonqrc
	cp -vf /etc/skel/kuriikwsfilterrc ${mountpoint}/home/${user_name}/.kde4/share/config/kuriikwsfilterrc
	cp -vf /etc/skel/kdeglobals ${mountpoint}/home/${user_name}/.kde4/share/config/kdeglobals
	cp -vf /etc/skel/oxygenrc ${mountpoint}/home/${user_name}/.kde4/share/config/oxygenrc
        cp -vf /etc/skel/yakuakerc ${mountpoint}/home/${user_name}/.kde4/share/config/yakuakerc
        cp -vf /etc/skel/kickoffrc ${mountpoint}/home/${user_name}/.kde4/share/config/kickoffrc
	cp -vf /etc/skel/networkmanagementrc ${mountpoint}/home/${user_name}/.kde4/share/config/networkmanagementrc
	cp -vf /etc/skel/.bashrc ${mountpoint}/home/${user_name}/.bashrc
	cp -vf /etc/skel/mimeapps.list ${mountpoint}/home/${user_name}/.local/share/applications/mimeapps.list
	cp -vf /etc/skel/duckduckgo.desktop ${mountpoint}/home/${user_name}/.kde4/share/kde4/services/searchproviders/duckduckgo.desktop
	cp -vf /etc/skel/kapudan.desktop ${mountpoint}/home/${user_name}/.config/autostart/kapudan.desktop
	cp -vf /etc/skel/katerc ${mountpoint}/home/${user_name}/.kde4/share/config/katerc

	chroot ${mountpoint} ln -sf /usr/bin/bluedevil-monolithic /home/${user_name}/.kde4/Autostart/bluedevil-monolithic

	# fix quirks
	if [ -e "${mountpoint}/home/${user_name}/10-keyboard.conf" ] ; then
	  msg "clean 10-keyboard.conf"
	  rm -v ${mountpoint}/home/${user_name}/10-keyboard.conf
	fi

	if [ -e "${mountpoint}/home/${user_name}/mirrorlist" ] ; then
	  msg "clean mirrorlist"
	  rm -v ${mountpoint}/home/${user_name}/mirrorlist
	fi
	
	# fix SUID to capable permissions on iputils
        setcap cap_net_raw=ep ${mountpoint}/usr/bin/ping  2>/dev/null || chmod +s ${mountpoint}/usr/bin/ping 
        setcap cap_net_raw=ep ${mountpoint}/usr/bin/ping6 2>/dev/null || chmod +s ${mountpoint}/usr/bin/ping6

	msg "ensure correct sudoers permissions"
	echo "%bundle ALL=NOPASSWD: /bin/mount -o loop -t squashfs *" >> ${mountpoint}/etc/sudoers
	echo "%bundle ALL=NOPASSWD: /bin/mount -o loop -t ext4 *" >> ${mountpoint}/etc/sudoers
	echo "%bundle ALL=NOPASSWD: /bin/umount *" >> ${mountpoint}/etc/sudoers
	echo "%bundle ALL=NOPASSWD: /usr/bin/pacman -Sy" >> ${mountpoint}/etc/sudoers
	chmod -v 0440 ${mountpoint}/etc/sudoers

	msg "chown ${user_name} /home/${user_name}"
	chroot ${mountpoint} /bin/chown -v ${user_name}:users /home/${user_name}
	chroot ${mountpoint} /bin/chown -vR ${user_name}:users /home/${user_name}/Desktop
	chroot ${mountpoint} /bin/chown -vR ${user_name}:users /home/${user_name}/Downloads
	chroot ${mountpoint} /bin/chown -vR ${user_name}:users /home/${user_name}/Images
	chroot ${mountpoint} /bin/chown -vR ${user_name}:users /home/${user_name}/Music
	chroot ${mountpoint} /bin/chown -vR ${user_name}:users /home/${user_name}/Video
	msg "chown ${user_name} /home/${user_name}/.*"
	chroot ${mountpoint} /usr/bin/find /home/${user_name}/ -maxdepth 1 -name '.*' -exec /bin/chown -vR ${user_name}:users '{}' \;

	msg_job_done "job_configure_users"
}
