#!/bin/bash

job_cleanup_l10n()
{
	# initialize error handling
	trap error_handler ERR

	msg_job_start "job_cleanup_l10n"

        trap 'api_fs_umount "${mountpoint}" 2>/dev/null' EXIT
        api_fs_mount "${mountpoint}"

	# remove any db.lck
	chroot ${mountpoint} /bin/rm -f /var/lib/pacman/db.lck
	
	#
	# CLEANUP UP LOCALIZATION
	#
	USED_L10N=${kdelang}
	ALL_L10N=$(pacman -r ${mountpoint} -Q | grep ${KDE_L10N_PREFIX} | cut -d " " -f 1 | awk -F "l10n-" '{print $2}')

	msg "configured localization: ${USED_L10N}"
	msg "installed localization(s): ${ALL_L10N}"

            for l10npkg in ${ALL_L10N}
            do
                    if [ "${l10npkg}" != "$USED_L10N" ] ; then
                            pacman -r ${mountpoint} -Rddn kde-l10n-${l10npkg} --noconfirm
                    fi
            done

	#
	# CLEANUP UP LOCALIZATION CALLIGRA
	#
	USED_L10N=${kdelang}
	ALL_L10NC=$(pacman -r ${mountpoint} -Q | grep ${CALLIGRA_L10N_PREFIX} | cut -d " " -f 1 | awk -F "l10n-" '{print $2}')

	msg "configured localization: ${USED_L10N}"
	msg "installed calligra localization(s): ${ALL_L10NC}"

            for l10ncpkg in ${ALL_L10NC}
            do
                    if [ "${l10ncpkg}" != "$USED_L10N" ] ; then
                            pacman -r ${mountpoint} -Rddn calligra-l10n-${l10ncpkg} --noconfirm
                    fi
            done

	msg "l10n removal complete"
	
	msg "set additional home dirs"
	chroot ${mountpoint} xdg-user-dirs-update ${user_name}

	msg_job_done "job_cleanup_l10n"
}
