# - Try to find marblewidget library
# Once done this will define
#
#  INSTALLERPARTITIONMANAGER_FOUND - system has INSTALLERPARTITIONMANAGER library
#  INSTALLERPARTITIONMANAGER_INCLUDE_DIR - the INSTALLERPARTITIONMANAGER include directory
#  INSTALLERPARTITIONMANAGER_LIBRARY - the marblewidget library
#
#  copyright 2008 by Patrick Spendrin <ps_ml@gmx.de>
#  use this file as you like
#

if(INSTALLERPARTITIONMANAGER_INCLUDE_DIR AND INSTALLERPARTITIONMANAGER_LIBRARY)

  # Already in cache
  set(INSTALLERPARTITIONMANAGER_FOUND TRUE)

else(INSTALLERPARTITIONMANAGER_INCLUDE_DIR AND INSTALLERPARTITIONMANAGER_LIBRARY)
  find_path(INSTALLERPARTITIONMANAGER_INCLUDE_DIR core/partition.h PATH_SUFFIXES installerpartitionmanager)

  find_library(INSTALLERPARTITIONMANAGER_LIBRARY installerpartitionmanager)

  if(INSTALLERPARTITIONMANAGER_INCLUDE_DIR AND INSTALLERPARTITIONMANAGER_LIBRARY)
    set(INSTALLERPARTITIONMANAGER_FOUND TRUE)
  endif(INSTALLERPARTITIONMANAGER_INCLUDE_DIR AND INSTALLERPARTITIONMANAGER_LIBRARY)

  if(INSTALLERPARTITIONMANAGER_FOUND)
    if (NOT INSTALLERPARTITIONMANAGER_FIND_QUIETLY)
      message(STATUS "Found custom PartitionManager for Installer by Dario (tm): ${INSTALLERPARTITIONMANAGER_LIBRARY}")
    endif (NOT INSTALLERPARTITIONMANAGER_FIND_QUIETLY)
  else(INSTALLERPARTITIONMANAGER_FOUND)
    if(INSTALLERPARTITIONMANAGER_FIND_REQUIRED)
      message(FATAL_ERROR "Could NOT find any PartitionManager for Installer by Dario (tm) library")
    endif(INSTALLERPARTITIONMANAGER_FIND_REQUIRED)
  endif(INSTALLERPARTITIONMANAGER_FOUND)

  mark_as_advanced(INSTALLERPARTITIONMANAGER_INCLUDE_DIR INSTALLERPARTITIONMANAGER_LIBRARY)
endif(INSTALLERPARTITIONMANAGER_INCLUDE_DIR AND INSTALLERPARTITIONMANAGER_LIBRARY)
